development:
  bucket: SweetSpeeches_development
  access_key_id: AKIAJP65PDDBGMD56ERA
  secret_access_key: 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
# test:
  # access_key_id: abc...
  # secret_access_key: abc...
# production:
  # access_key_id: 456...
  # secret_access_key: 456...